# Advanced Certification Program in Computational Data Science
## A program by IISc and TalentSprint
### Mini Project Notebook: Linear Algebra and Calculus

## Problem Statement

 The task is to advise a petroleum company on how to meet the demands of their customers for motor oil, diesel oil and gasoline.

## Learning Objectives

At the end of the experiment, you will be able to

* create arrays and matrices in python
* understand the concepts of linear equations
* solve the system of linear equations

### Data

From a barrel of crude oil, in one day, factory $A$ can produce
* 20 gallons of motor oil,
* 10 gallons of diesel oil, and
* 5 gallons of gasoline

Similarly, factory $B$ can produce
* 4 gallons of motor oil,
* 14 gallons of diesel oil, and
* 5 gallons of gasoline

while factory $C$ can produce
* 4 gallons of motor oil,
* 5 gallons of diesel oil, and
* 12 gallons of gasoline

There is also waste in the form of paraffin, among other things. Factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude, factory $B$ 5 gallons, and factory $C$ 2 gallons.

**Note:** Your conclusion should include a discussion of the nature of the terms *unique*, *no solution*, *overdetermined* and *underdetermined* as they apply in the context of the oil plants.

## Grading = 10 Points

### Create an array

Create an array of size 2x3 with arbitrary values.

In [ ]:
# YOUR CODE HERE
import numpy as np

# Create a 2x3 array with arbitrary values
array_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
print("2x3 Array:")
print(array_2x3)

2x3 Array:
[[1 2 3]
 [4 5 6]]


### Create the system of Linear Equations

Suppose the current daily demand from distributors is 6600 gallons of motor oil, 5100 gallons of diesel oil and 3100 of gasoline.

Set up the system of equations which describes the above situation. Please include the units as well.

Let the number of barrels used by factory $A$, $B$ and $C$ are $x$, $y$ and $z$ respectively.

Then the system of linear equations will be

$$Motor\ oil:\ \ \ 20x + 4y + 4z = 6600$$

$$Diesel\ oil:\ \ \ 10x + 14y + 5z = 5100$$

$$Gasoline:\ \ \ 5x + 5y + 12z = 3100$$

### Solve the system of Linear Equation (2 points)

How many barrels of crude oil each plant should get in order to meet the demand as a group. Remember that we can only provide each plant with an integral number of barrels.

In [ ]:
# YOUR CODE HERE
from numpy.linalg import solve

# Coefficients matrix (motor oil, diesel oil, gasoline for each factory)
A = np.array([
    [20, 4, 4],    # Motor oil production per barrel
    [10, 14, 5],   # Diesel oil production per barrel
    [5, 5, 12]     # Gasoline production per barrel
])

# Demand vector (in gallons)
b = np.array([6600, 5100, 3100])

# Solve the system of equations
x = solve(A, b)
print("Solution (barrels for each factory):")
print(f"Factory A: {x[0]}")
print(f"Factory B: {x[1]}")
print(f"Factory C: {x[2]}")

# Round to nearest integer since we can only provide whole barrels
x_rounded = np.round(x).astype(int)
print("\nRounded solution (whole barrels):")
print(f"Factory A: {x_rounded[0]}")
print(f"Factory B: {x_rounded[1]}")
print(f"Factory C: {x_rounded[2]}")

# Check if rounded solution meets demand
production = A @ x_rounded
print("\nProduction with rounded solution:")
print(f"Motor oil: {production[0]} gallons (demand: {b[0]})")
print(f"Diesel oil: {production[1]} gallons (demand: {b[1]})")
print(f"Gasoline: {production[2]} gallons (demand: {b[2]})")

Solution (barrels for each factory):
Factory A: 287.25
Factory B: 128.75
Factory C: 85.0

Rounded solution (whole barrels):
Factory A: 287
Factory B: 129
Factory C: 85

Production with rounded solution:
Motor oil: 6596 gallons (demand: 6600)
Diesel oil: 5101 gallons (demand: 5100)
Gasoline: 3100 gallons (demand: 3100)


Suppose the total demand for all products **doubled**. What would the solution now be? How does it compare to the original solution? Why, mathematically, should this have been expected?

In [ ]:
# YOUR CODE HERE
# Double the demand
b_doubled = 2 * b

# Solve with doubled demand
x_doubled = solve(A, b_doubled)
print("\nSolution for doubled demand:")
print(f"Factory A: {x_doubled[0]}")
print(f"Factory B: {x_doubled[1]}")
print(f"Factory C: {x_doubled[2]}")

# Round to nearest integer
x_doubled_rounded = np.round(x_doubled).astype(int)
print("\nRounded solution for doubled demand:")
print(f"Factory A: {x_doubled_rounded[0]}")
print(f"Factory B: {x_doubled_rounded[1]}")
print(f"Factory C: {x_doubled_rounded[2]}")

# Compare with original solution
print("\nComparison with original solution:")
print(f"Factory A: {x_doubled_rounded[0]} vs {x_rounded[0]} (ratio: {x_doubled_rounded[0]/x_rounded[0] if x_rounded[0] != 0 else 'N/A'})")
print(f"Factory B: {x_doubled_rounded[1]} vs {x_rounded[1]} (ratio: {x_doubled_rounded[1]/x_rounded[1] if x_rounded[1] != 0 else 'N/A'})")
print(f"Factory C: {x_doubled_rounded[2]} vs {x_rounded[2]} (ratio: {x_doubled_rounded[2]/x_rounded[2] if x_rounded[2] != 0 else 'N/A'})")
print("\nMathematically, we expect the solution to double when the demand doubles because this is a linear system.")


Solution for doubled demand:
Factory A: 574.5
Factory B: 257.5
Factory C: 170.0

Rounded solution for doubled demand:
Factory A: 574
Factory B: 258
Factory C: 170

Comparison with original solution:
Factory A: 574 vs 287 (ratio: 2.0)
Factory B: 258 vs 129 (ratio: 2.0)
Factory C: 170 vs 85 (ratio: 2.0)

Mathematically, we expect the solution to double when the demand doubles because this is a linear system.


Suppose that the company acquires another group of distributors and that the daily demand of this group is 2000 gallons of motor oil, 4000 gallons of gasoline, and 4000 gallons of diesel oil. How would you set up production of just this supply? Are there any options (more than one way)?

In [ ]:
# YOUR CODE HERE
# New demand from the second group of distributors
b_new = np.array([2000, 4000, 4000])

# Solve for this new demand
x_new = solve(A, b_new)
print("\nSolution for new group of distributors:")
print(f"Factory A: {x_new[0]}")
print(f"Factory B: {x_new[1]}")
print(f"Factory C: {x_new[2]}")

# Round to nearest integer
x_new_rounded = np.round(x_new).astype(int)
print("\nRounded solution for new group:")
print(f"Factory A: {x_new_rounded[0]}")
print(f"Factory B: {x_new_rounded[1]}")
print(f"Factory C: {x_new_rounded[2]}")

# Check if there are multiple solutions (by checking if the matrix is singular)
if np.linalg.matrix_rank(A) < A.shape[1]:
    print("\nThe coefficient matrix is not full rank, so there are multiple solutions.")
else:
    print("\nThe coefficient matrix is full rank, so there is a unique solution.")

# Total demand from both groups
b_total = b + b_new
print("\nTotal demand from both groups:")
print(f"Motor oil: {b_total[0]} gallons")
print(f"Diesel oil: {b_total[1]} gallons")
print(f"Gasoline: {b_total[2]} gallons")

# Solve for total demand
x_total = solve(A, b_total)
print("\nSolution for total demand:")
print(f"Factory A: {x_total[0]}")
print(f"Factory B: {x_total[1]}")
print(f"Factory C: {x_total[2]}")

# Round to nearest integer
x_total_rounded = np.round(x_total).astype(int)
print("\nRounded solution for total demand:")
print(f"Factory A: {x_total_rounded[0]}")
print(f"Factory B: {x_total_rounded[1]}")
print(f"Factory C: {x_total_rounded[2]}")




Solution for new group of distributors:
Factory A: 12.5
Factory B: 187.5
Factory C: 250.0

Rounded solution for new group:
Factory A: 12
Factory B: 188
Factory C: 250

The coefficient matrix is full rank, so there is a unique solution.

Total demand from both groups:
Motor oil: 8600 gallons
Diesel oil: 9100 gallons
Gasoline: 7100 gallons

Solution for total demand:
Factory A: 299.75
Factory B: 316.25
Factory C: 335.0

Rounded solution for total demand:
Factory A: 300
Factory B: 316
Factory C: 335


Next, calculate the needs of each factory (in barrels of crude, as usual) to meet the total demand of both groups of distributors. When you have done this, compare your answer to results already obtained. What mathematical conclusion can you draw?

In [ ]:
# YOUR CODE HERE
# Compare with sum of individual solutions
x_sum = x_rounded + x_new_rounded
print("\nComparison with sum of individual solutions:")
print(f"Factory A: {x_total_rounded[0]} vs {x_sum[0]}")
print(f"Factory B: {x_total_rounded[1]} vs {x_sum[1]}")
print(f"Factory C: {x_total_rounded[2]} vs {x_sum[2]}")
print("\nMathematically, we expect these to be equal since linear systems follow the principle of superposition.")


Comparison with sum of individual solutions:
Factory A: 300 vs 299
Factory B: 316 vs 317
Factory C: 335 vs 335

Mathematically, we expect these to be equal since linear systems follow the principle of superposition.


### Sensitivity and Robustness (1 point)

In real life applications, constants are rarely ever exactly equal to their stated value; certain amounts of uncertainty are always present. This is part of the reason for the science of statistics. In the above model, the daily productions for the plants would be averages over a period of time. Explore what effect small changes in the parameters have on the output.

To do this, pick any 3 coefficients, one at a time, and increase or decrease them by 3%. For each case , note what effect this has on the solution, as a percentage change. Can you draw any overall conclusion?

In [ ]:
# YOUR CODE HERE
def perturb_coefficient(A, b, row, col, percent_change):
    """Perturb a coefficient and solve the system"""
    A_perturbed = A.copy()
    # Modify one coefficient by the given percentage
    original_value = A_perturbed[row, col]
    A_perturbed[row, col] = original_value * (1 + percent_change/100)

    # Solve the perturbed system
    x_perturbed = solve(A_perturbed, b)

    return x_perturbed

# Original solution
x_original = solve(A, b)

# Perturb three different coefficients by +3% and -3%
perturbations = [
    (0, 0, 3),    # Increase first coefficient by 3%
    (1, 1, 3),    # Increase second coefficient by 3%
    (2, 2, 3),    # Increase third coefficient by 3%
    (0, 0, -3),   # Decrease first coefficient by 3%
    (1, 1, -3),   # Decrease second coefficient by 3%
    (2, 2, -3),   # Decrease third coefficient by 3%
]

print("\nSensitivity Analysis:")
for row, col, percent in perturbations:
    x_perturbed = perturb_coefficient(A, b, row, col, percent)

    # Calculate percentage change in solution
    percent_change = 100 * (x_perturbed - x_original) / x_original

    print(f"\nPerturbing A[{row},{col}] by {percent}%:")
    print(f"Original value: {A[row,col]}, New value: {A[row,col] * (1 + percent/100)}")
    print(f"Original solution: {x_original}")
    print(f"Perturbed solution: {x_perturbed}")
    print(f"Percentage change in solution:")
    print(f"  Factory A: {percent_change[0]:.2f}%")
    print(f"  Factory B: {percent_change[1]:.2f}%")
    print(f"  Factory C: {percent_change[2]:.2f}%")


Sensitivity Analysis:

Perturbing A[0,0] by 3%:
Original value: 20, New value: 20.6
Original solution: [287.25 128.75  85.  ]
Perturbed solution: [287.25 128.75  85.  ]
Percentage change in solution:
  Factory A: 0.00%
  Factory B: 0.00%
  Factory C: 0.00%

Perturbing A[1,1] by 3%:
Original value: 14, New value: 14.42
Original solution: [287.25 128.75  85.  ]
Perturbed solution: [287.25 128.75  85.  ]
Percentage change in solution:
  Factory A: 0.00%
  Factory B: 0.00%
  Factory C: 0.00%

Perturbing A[2,2] by 3%:
Original value: 12, New value: 12.36
Original solution: [287.25 128.75  85.  ]
Perturbed solution: [287.25 128.75  85.  ]
Percentage change in solution:
  Factory A: 0.00%
  Factory B: 0.00%
  Factory C: 0.00%

Perturbing A[0,0] by -3%:
Original value: 20, New value: 19.4
Original solution: [287.25 128.75  85.  ]
Perturbed solution: [305.44971201 116.65928223  82.45458573]
Percentage change in solution:
  Factory A: 6.34%
  Factory B: -9.39%
  Factory C: -2.99%

Perturbing A[

### A Plant Off-Line (1 point)

Suppose factory $C$ is shut down by the EPA (Environmental Protection Agency) temporarily for excessive emissions into the atmosphere. If your demand is as it was originally (6600, 5100, 3100), what would you now say about the companies ability to meet it? What do you recommend they schedule for production now?

In [ ]:
# YOUR CODE HERE
# Factory C is shut down - we're left with just factories A and B
A_reduced = A[:, 0:2]  # First two columns of A
print("\nCoefficient matrix with only factories A and B:")
print(A_reduced)

# Check if the reduced system is solvable
if np.linalg.matrix_rank(A_reduced) < np.linalg.matrix_rank(np.column_stack([A_reduced, b])):
    print("\nThe reduced system is inconsistent - no exact solution exists.")

    # We can find the least squares solution
    x_ls, residuals, rank, s = np.linalg.lstsq(A_reduced, b, rcond=None)
    print("\nLeast squares solution:")
    print(f"Factory A: {x_ls[0]}")
    print(f"Factory B: {x_ls[1]}")

    # Round to nearest integers
    x_ls_rounded = np.round(x_ls).astype(int)
    print("\nRounded least squares solution:")
    print(f"Factory A: {x_ls_rounded[0]}")
    print(f"Factory B: {x_ls_rounded[1]}")

    # Check production with this solution
    production_ls = A_reduced @ x_ls_rounded
    print("\nProduction with least squares solution:")
    print(f"Motor oil: {production_ls[0]} gallons (demand: {b[0]})")
    print(f"Diesel oil: {production_ls[1]} gallons (demand: {b[1]})")
    print(f"Gasoline: {production_ls[2]} gallons (demand: {b[2]})")

    # Calculate shortfall/excess
    shortfall = b - production_ls
    print("\nShortfall (-) or excess (+):")
    print(f"Motor oil: {shortfall[0]} gallons")
    print(f"Diesel oil: {shortfall[1]} gallons")
    print(f"Gasoline: {shortfall[2]} gallons")

else:
    print("\nThe reduced system is consistent - an exact solution exists.")
    x_reduced = solve(A_reduced, b)
    print("\nSolution:")
    print(f"Factory A: {x_reduced[0]}")
    print(f"Factory B: {x_reduced[1]}")


Coefficient matrix with only factories A and B:
[[20  4]
 [10 14]
 [ 5  5]]

The reduced system is inconsistent - no exact solution exists.

Least squares solution:
Factory A: 299.4720496894411
Factory B: 168.4782608695653

Rounded least squares solution:
Factory A: 299
Factory B: 168

Production with least squares solution:
Motor oil: 6652 gallons (demand: 6600)
Diesel oil: 5342 gallons (demand: 5100)
Gasoline: 2335 gallons (demand: 3100)

Shortfall (-) or excess (+):
Motor oil: -52 gallons
Diesel oil: -242 gallons
Gasoline: 765 gallons


### Buying another plant

####(Note the following given information. You will see questions in continuation to this, in the subsequent sections)

This situation has caused enough concern that the CEO is considering buying another plant, identical to the third, and using it permanently. Assuming that all 4 plants are on line, what production do you recommend to meet the current demand (5000, 8500, 10000)? In general, what can you say about any increased flexibility that the 4th plant might provide?

Let the number of barrels used by factory $A$, $B$, $C$ and $D$ are $x$, $y$, $z$ and $w$ respectively.

Then the system of linear equations will be

$$20x + 4y + 4z + 4w = 5000$$

$$10x + 14y + 5z + 5w = 8500$$

$$5x + 5y + 12z + 12w = 10000$$

The above system of linear equation has fewer equations than variables, hence it is *underdetermined* and cannot have a unique solution. In this case, there are either infinitely many solutions or no exact solution. We can solve it by keeping $w$ as constant and using [rref](http://linear.ups.edu/html/section-RREF.html) form to solve the system of linear equation.

To know about rref implementation in python refer [here](https://docs.sympy.org/latest/tutorial/matrices.html#rref).

In [ ]:
import sympy as sy

# create symbol 'w'
w = sy.Symbol("w")
A_aug = sy.Matrix([[20, 4, 4, 5000-4*w],
                   [10, 14, 5, 8500-5*w],
                   [5, 5, 12, 10000-12*w]])
# show rref form
A_aug.rref()

(Matrix([
 [1, 0, 0,   195/4],
 [0, 1, 0,  1325/4],
 [0, 0, 1, 675 - w]]),
 (0, 1, 2))

In [ ]:
import sympy as sy

# Create symbol 'w'
w = sy.Symbol("w")
current_demand = np.array([5000, 8500, 10000])

# Create the augmented matrix for RREF
A_aug = sy.Matrix([
    [20, 4, 4, 5000-4*w],
    [10, 14, 5, 8500-5*w],
    [5, 5, 12, 10000-12*w]
])

# Show the RREF form
rref_result = A_aug.rref()
print("\nRow Reduced Echelon Form:")
print(rref_result[0])

# Let's try a specific value for w (e.g., w = 100)
w_value = 100
A_four_plants = np.array([
    [20, 4, 4, 4],
    [10, 14, 5, 5],
    [5, 5, 12, 12]
])
b_new_demand = np.array([5000, 8500, 10000])

# The system is underdetermined (3 equations, 4 unknowns)
# Let's use NumPy's least squares solver with a regularization term to find a solution
A_transpose = A_four_plants.T
AtA = A_transpose @ A_four_plants
AtA_reg = AtA + 0.01 * np.eye(4)  # Add small regularization
Atb = A_transpose @ b_new_demand
x_solution = solve(AtA_reg, Atb)

print("\nA possible solution with the fourth plant (w =", w_value, "):")
print(f"Factory A: {x_solution[0]}")
print(f"Factory B: {x_solution[1]}")
print(f"Factory C: {x_solution[2]}")
print(f"Factory D: {x_solution[3]}")

# Round to nearest integer
x_solution_rounded = np.round(x_solution).astype(int)
print("\nRounded solution:")
print(f"Factory A: {x_solution_rounded[0]}")
print(f"Factory B: {x_solution_rounded[1]}")
print(f"Factory C: {x_solution_rounded[2]}")
print(f"Factory D: {x_solution_rounded[3]}")

# Check if this meets the demand
production = A_four_plants @ x_solution_rounded
print("\nProduction with this solution:")
print(f"Motor oil: {production[0]} gallons (demand: {b_new_demand[0]})")
print(f"Diesel oil: {production[1]} gallons (demand: {b_new_demand[1]})")
print(f"Gasoline: {production[2]} gallons (demand: {b_new_demand[2]})")


Row Reduced Echelon Form:
Matrix([[1, 0, 0, 195/4], [0, 1, 0, 1325/4], [0, 0, 1, 675 - w]])

A possible solution with the fourth plant (w = 100 ):
Factory A: 48.7636307529188
Factory B: 331.234031954972
Factory C: 337.49017997196955
Factory D: 337.49017997246176

Rounded solution:
Factory A: 49
Factory B: 331
Factory C: 337
Factory D: 337

Production with this solution:
Motor oil: 5000 gallons (demand: 5000)
Diesel oil: 8494 gallons (demand: 8500)
Gasoline: 9988 gallons (demand: 10000)


From the above result, it can be seen that 4th plant will share the number of barrels required by the 3rd plant only, while the requirement of 1st and 2nd plant will remain unaffected.

### Calculate the amount of Paraffin supplied (1 point)

The company has just found a candle company that will buy its paraffin. Under the current conditions (i.e, after buying another plant) for demand (5000, 8500, 10000), how much can be supplied to them per day?

According to the problem statement, factory $A$ has 3 gallons of paraffin to dispose of per barrel of crude oil, factory $B$ 5 gallons, and factory $C$ 2 gallons.

In [ ]:
# YOUR CODE HERE
# Paraffin per barrel for each factory
paraffin_per_barrel = np.array([3, 5, 2, 2])  # Factory A, B, C, D

# Total paraffin produced with the current solution
total_paraffin = np.dot(paraffin_per_barrel, x_solution_rounded)
print("\nTotal paraffin produced per day:")
print(f"{total_paraffin} gallons")


Total paraffin produced per day:
3150 gallons


### Selling the first plant (1 point)

The management is also considering selling the first plant due to aging equipment and high workman's compensation costs for the state it is located in. They would like to know what this would do to their production capability. Specifically, they would like an example of a demand they could not meet with only plants 2 and 3, and also what effect having plant 4 has (recall it is identical to plant 3). They would also like an example of a demand that they could meet with just plants 2 and 3. Any general statements you could make here would be helpful.

Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

When considering only plants 2 and 3, and demand (5000, 8500, 10000) then we have

$$4y + 4z = 5000$$

$$14y + 5z = 8500$$

$$5y + 12z = 10000$$

In [ ]:
# YOUR CODE HERE
# Consider only plants 2 and 3 (B and C)
A_BC = np.array([
    [4, 4],    # Motor oil production
    [14, 5],   # Diesel oil production
    [5, 12]    # Gasoline production
])

# Original demand
b_original = np.array([6600, 5100, 3100])

# Check if this system is solvable
if np.linalg.matrix_rank(A_BC) < np.linalg.matrix_rank(np.column_stack([A_BC, b_original])):
    print("\nWith only plants B and C, the original demand cannot be met exactly.")
else:
    print("\nWith only plants B and C, the original demand can be met exactly.")

# Find the least squares solution
x_BC, residuals, rank, s = np.linalg.lstsq(A_BC, b_original, rcond=None)
print("\nLeast squares solution with plants B and C:")
print(f"Factory B: {x_BC[0]}")
print(f"Factory C: {x_BC[1]}")

# Round to nearest integer
x_BC_rounded = np.round(x_BC).astype(int)
print("\nRounded solution:")
print(f"Factory B: {x_BC_rounded[0]}")
print(f"Factory C: {x_BC_rounded[1]}")

# Check production
production_BC = A_BC @ x_BC_rounded
print("\nProduction with plants B and C:")
print(f"Motor oil: {production_BC[0]} gallons (demand: {b_original[0]})")
print(f"Diesel oil: {production_BC[1]} gallons (demand: {b_original[1]})")
print(f"Gasoline: {production_BC[2]} gallons (demand: {b_original[2]})")

# Shortfall or excess
shortfall_BC = b_original - production_BC
print("\nShortfall (-) or excess (+):")
print(f"Motor oil: {shortfall_BC[0]} gallons")
print(f"Diesel oil: {shortfall_BC[1]} gallons")
print(f"Gasoline: {shortfall_BC[2]} gallons")

# With the new demand
b_new_demand = np.array([5000, 8500, 10000])
# Check if this system is solvable
if np.linalg.matrix_rank(A_BC) < np.linalg.matrix_rank(np.column_stack([A_BC, b_new_demand])):
    print("\nWith only plants B and C, the new demand cannot be met exactly.")
else:
    print("\nWith only plants B and C, the new demand can be met exactly.")


With only plants B and C, the original demand cannot be met exactly.

Least squares solution with plants B and C:
Factory B: 352.96284788494864
Factory C: 203.0671578853921

Rounded solution:
Factory B: 353
Factory C: 203

Production with plants B and C:
Motor oil: 2224 gallons (demand: 6600)
Diesel oil: 5957 gallons (demand: 5100)
Gasoline: 4201 gallons (demand: 3100)

Shortfall (-) or excess (+):
Motor oil: 4376 gallons
Diesel oil: -857 gallons
Gasoline: -1101 gallons

With only plants B and C, the new demand cannot be met exactly.


Taking 4th plant into consideration.
Let the number of barrels used by factory $B$, $C$ and $D$ are $y$, $z$ and $w$ respectively.

Then for demand (5000, 8500, 10000) the system of linear equations will be

$$4y + 4z + 4w = 5000$$

$$14y + 5z + 5w = 8500$$

$$5y + 12z + 12w = 10000$$

Solve it using rref form.

In [ ]:
# YOUR CODE HERE

Now, changing demand to (6600, 5100, 3100) and solving the system of equation using rref form.

In [ ]:
# YOUR CODE HERE

### Set rates for Products (1 point)

Company wants to set the rates of motor oil, diesel oil, and gasoline. For this purpose they have few suggestions given as follows:

* 100, 66, 102 Rupees per gallon,

* 104, 64, 100 Rupees per gallon,

* 102, 68, 98 Rupees per gallon, and

* 96, 68, 100 Rupees per gallon

for motor oil, diesel oil, and gasoline respectively.

Using matrix multiplication, find the rates which result in maximum total price.

Let $M$ denote the matrix such that rows represents different plants (A, B and C), columns represents different products (motor oil, diesel oil and gasoline) and each value represents production of that product from one barrel of crude oil for that plant.

$$M = \begin{bmatrix}
20 & 10 & 5 \\
4 & 14 & 5  \\
 4 & 5 & 12  
\end{bmatrix}$$

Also, $R$ is a matrix having different rates as its columns.

$$R = \begin{bmatrix}
100 & 104 & 102 & 96 \\
66 & 64 & 68 & 68  \\
102 & 100 & 98 & 100  
\end{bmatrix}$$

In [ ]:
# YOUR CODE HERE
# Define the production matrix
M = np.array([
    [20, 10, 5],  # Factory A
    [4, 14, 5],   # Factory B
    [4, 5, 12]    # Factory C
])

# Define the rates matrix
R = np.array([
    [100, 104, 102, 96],  # Motor oil
    [66, 64, 68, 68],     # Diesel oil
    [102, 100, 98, 100]   # Gasoline
])

# Calculate the production value for each rate set
production_values = M @ R
print("\nProduction values for each rate set:")
print(production_values)

# Find which rate set gives the maximum value for each factory
best_rate_index = np.argmax(production_values, axis=1)
print("\nBest rate set index for each factory:")
print(f"Factory A: {best_rate_index[0]} (value: {production_values[0, best_rate_index[0]]})")
print(f"Factory B: {best_rate_index[1]} (value: {production_values[1, best_rate_index[1]]})")
print(f"Factory C: {best_rate_index[2]} (value: {production_values[2, best_rate_index[2]]})")

# Calculate total production value for each rate set
total_production_value = np.sum(production_values, axis=0)
print("\nTotal production value for each rate set:")
print(total_production_value)

# Find which rate set gives the maximum total value
best_overall_rate_index = np.argmax(total_production_value)
print(f"\nBest overall rate set: {best_overall_rate_index+1} with total value {total_production_value[best_overall_rate_index]}")
print(f"This corresponds to rates of {R[0, best_overall_rate_index]}, {R[1, best_overall_rate_index]}, {R[2, best_overall_rate_index]} Rupees per gallon")
print(f"for motor oil, diesel oil, and gasoline respectively.")


Production values for each rate set:
[[3170 3220 3210 3100]
 [1834 1812 1850 1836]
 [1954 1936 1924 1924]]

Best rate set index for each factory:
Factory A: 1 (value: 3220)
Factory B: 2 (value: 1850)
Factory C: 0 (value: 1954)

Total production value for each rate set:
[6958 6968 6984 6860]

Best overall rate set: 3 with total value 6984
This corresponds to rates of 102, 68, 98 Rupees per gallon
for motor oil, diesel oil, and gasoline respectively.


### Marginal Cost (1 point)

The total cost $C(x)$ in Rupees, associated with the production of $x$ gallons of gasoline is given by

$$C(x) = 0.005 x^3 – 0.02 x^2 + 30x + 5000$$

Find the marginal cost when $22$ gallons are produced, where, marginal cost means the instantaneous rate of change of total cost at any level of output.

In [ ]:
# YOUR CODE HERE
import sympy as sp

# Define the variable
x = sp.Symbol('x')

# Define the cost function
C = 0.005 * x**3 - 0.02 * x**2 + 30*x + 5000

# Calculate the derivative (marginal cost)
marginal_cost = sp.diff(C, x)
print("\nMarginal cost function:")
print(marginal_cost)

# Evaluate at x = 22
marginal_cost_at_22 = marginal_cost.subs(x, 22)
print(f"\nMarginal cost at x = 22 gallons: {marginal_cost_at_22} Rupees per gallon")


Marginal cost function:
0.015*x**2 - 0.04*x + 30

Marginal cost at x = 22 gallons: 36.3800000000000 Rupees per gallon


### Marginal Revenue (1 point)

The total revenue in Rupees received from the sale of $x$ gallons of a motor oil is given by $$R(x) = 3x^2 + 36x + 5.$$

Find the marginal revenue, when $x = 28$, where, marginal revenue means the rate of change of total revenue with respect to the number of items sold at an instant.

In [ ]:
# YOUR CODE HERE
# Define the revenue function
R = 3 * x**2 + 36*x + 5

# Calculate the derivative (marginal revenue)
marginal_revenue = sp.diff(R, x)
print("\nMarginal revenue function:")
print(marginal_revenue)

# Evaluate at x = 28
marginal_revenue_at_28 = marginal_revenue.subs(x, 28)
print(f"\nMarginal revenue at x = 28 gallons: {marginal_revenue_at_28} Rupees per gallon")


Marginal revenue function:
6*x + 36

Marginal revenue at x = 28 gallons: 204 Rupees per gallon


### Pouring crude oil in tank (1 point)

In a cylindrical tank of radius 10 meter, crude oil is being poured at the rate of 314 cubic meter per hour. Then find

* the rate at which the height of crude oil is increasing in the tank, and
* the height of crude oil in tank after 2 hours.

In [ ]:
# YOUR CODE HERE
import math

# Given values
radius = 10  # meters
flow_rate = 314  # cubic meters per hour

# Calculate rate of height increase
# For a cylinder: Volume = π * r^2 * h
# Therefore: dh/dt = (dV/dt) / (π * r^2)
height_increase_rate = flow_rate / (math.pi * radius**2)
print("\nRate of height increase:")
print(f"{height_increase_rate} meters per hour")

# Calculate height after 2 hours
height_after_2_hours = height_increase_rate * 2
print(f"\nHeight of crude oil after 2 hours: {height_after_2_hours} meters")


Rate of height increase:
0.9994930426171027 meters per hour

Height of crude oil after 2 hours: 1.9989860852342054 meters
